[package]
name = "fractulate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive", "env"] }
nalgebra = "0.33.2"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
stl_io = "0.8.3"
